[package]
name = "lithograph-extension"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "lithograph"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
lithograph-core = { path = "../lithograph-core", version = "=0.1.0" }
rusqlite = { workspace = true, features = ["functions", "loadable_extension", "vtab"] }
serde_json.workspace = true

[lints]
workspace = true
